image: crisu83/docker-nginx-php-node

services:
  - mysql:latest

stages:
  - production

deploy:
  image: crisu83/docker-nginx-php-node
  script:
    - apt-get update
    - apt-get install -y zlib1g-dev lftp
    - docker-php-ext-install zip
    - docker-php-ext-install mbstring
    - docker-php-ext-install pdo_mysql
    - php -v
    - conposer install --no-progress --no-interaction
    - npm install
    - lftp -e "mirror -R . $DEPLOY_FTP_DIR" -u $DEPLOY_FTP_USER,$DEPLOY_FTP_PASSWORD $DEPLOY_FTP_HOST