image: crisu83/docker-nginx-php-node
services:
  - mysql:latest
variables:
  WITH_XDEBUG: "1"
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_DATABASE: homestead
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  COMPOSER_HOME: /cache/composer
deploy:
  image: crisu83/docker-nginx-php-node
  script:
    - php -v
    - curl -sL https://deb.nodesource.com/setup_6.x | bash -
    - apt-get install -y build-essential nodejs lftp git-ftp sshpass
    - mkdir -p ~/.lftp
    - echo "set ssl:verify-certificate no" >> ~/.lftp/rc
    - composer install --no-progress --no-interaction
    - npm install -q
    - npm run --silent bower
    - npm run gulp
    - git config git-ftp.url ftp://$DEPLOY_FTP_HOST/$DEPLOY_FTP_DIR
    - git config git-ftp.user $DEPLOY_FTP_USER
    - git config git-ftp.password $DEPLOY_FTP_PASSWORD
    - git ftp push
    - lftp -e "mirror -R ./public/assets/ $DEPLOY_FTP_DIR/public/assets/ --parallel=10" -u $DEPLOY_FTP_USER,$DEPLOY_FTP_PASSWORD $DEPLOY_FTP_HOST
    - sshpass -p $DEPLOY_FTP_PASSWORD ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $DEPLOY_FTP_USER@$DEPLOY_FTP_HOST "cd $DEPLOY_FTP_DIR && php artisan migrate --force"
  only:
    - master