image: crisu83/docker-nginx-php-node
services:
  - mysql:latest
variables:
  WITH_XDEBUG: "1"
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_DATABASE: homestead
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  COMPOSER_HOME: /cache/composer
deploy:
  image: crisu83/docker-nginx-php-node
  script:
    - php -v
    - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - sudo apt-get install -y build-essential nodejs lftp
    - composer install --no-progress --no-interaction
    - lftp -e "mirror -R . $DEPLOY_FTP_DIR --parallel=10 --exclude-glob .git* --exclude .git/" -u $DEPLOY_FTP_USER,$DEPLOY_FTP_PASSWORD $DEPLOY_FTP_HOST
  only:
    - master