services:
  - mysql:latest
variables:
  WITH_XDEBUG: "1"
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_DATABASE: homestead
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  COMPOSER_HOME: /cache/composer
deploy:
  script:
    - apt-get update
    - apt-get install -y sshpass
    - sshpass -p$DEPLOY_FTP_PASSWORD ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $DEPLOY_FTP_USER@$DEPLOY_FTP_HOST "cd $DEPLOY_FTP_DIR && ./deploy.sh"
  only:
    - master