image: php:7.0-cli

services:
  - mysql:latest

stages:
  - production

deploy:
  type: deploy
  image: php:7.0-cli
  script:
    - apt-get update
    - apt-get install -y zlib1g-dev lftp
    - docker-php-ext-install zip
    - docker-php-ext-install mbstring
    - docker-php-ext-install pdo_mysql
    - ping -c 3 mysql
    - php -v
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install --no-progress --no-interaction
    - lftp -e "mirror -R . $DEPLOY_FTP_DIR" -u $DEPLOY_FTP_USER,$DEPLOY_FTP_PASSWORD $DEPLOY_FTP_HOST